### ISSUE TITLE
route "count" exist but "countAll" not implemented in controllers

### ISSUE THREAD

**Issue by trenaud** [telosys-templates-v3/javascript-web-rest-nodejs-express#1]
Hi,
After generating the code with this template, I found that the route "api/v1/my_entity/count" is created, but the countAll function is not implemented in entity controller.

When calling "http://localhost:3000/api/v1/corde/count" I got this error :
`TypeError: cordeController.countAll is not a function
    at D:\TRISTAN\workspace\GEPI2\app\routes\api\CordeRoutes.js:19:21
    at Layer.handle [as handle_request] (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\layer.js:95:5)
    at D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:335:12)
    at next (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:174:3)
    at router (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:317:13)
    at D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:335:12)
    at next (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\TRISTAN\workspace\GEPI2\node_modules\express\lib\router\index.js:174:3)`

**Comment by imadhy** [comment]
The function 'count' is not implemented yet because we still need to review the path that we are going to call to get count of an entity.
